version: 1
groups:
- id: default
  name: Камеры
  collapsed: false
  order: 0
  blocks:
  - id: cam_11
    title: CAM 11
    command_on: port set 1 1
    command_off: port clear 1 1
    send_to_combo: true
    order: 0
    mode: dual
    icon: null
    port: cpu1
    hotkey: null
    group_id: default
  - id: cam_12
    title: CAM 12
    command_on: port set 1 2
    command_off: port clear 1 2
    send_to_combo: true
    order: 1
    mode: dual
    icon: null
    port: combo
    hotkey: null
    group_id: default
  - id: cam_13
    title: CAM 13
    command_on: port set 1 3
    command_off: port clear 1 3
    send_to_combo: true
    order: 2
    mode: dual
    icon: null
    port: combo
    hotkey: null
    group_id: default
  - id: cam_14
    title: CAM 14
    command_on: port set 2 4
    command_off: port clear 2 4
    send_to_combo: true
    order: 3
    mode: dual
    icon: null
    port: combo
    hotkey: null
    group_id: default
  - id: cam_15
    title: CAM 15
    command_on: port set 2 5
    command_off: port clear 2 5
    send_to_combo: true
    order: 4
    mode: dual
    icon: null
    port: combo
    hotkey: null
    group_id: default
- id: default
  name: BeagleBone
  collapsed: false
  order: 1
  blocks:
  - id: bb_a
    title: BB A
    command_on: bb a on
    command_off: bb a off
    send_to_combo: true
    order: 0
    mode: dual
    icon: null
    port: combo
    hotkey: null
    group_id: default
  - id: bb_b
    title: BB B
    command_on: bb b on
    command_off: bb b off
    send_to_combo: true
    order: 1
    mode: dual
    icon: null
    port: combo
    hotkey: null
    group_id: default
